name: signal_vip_pp
description: simple VIP signal project with Flutter.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
    
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
flutter:

  uses-material-design: true

  assets:
    - images/w.png
    - images/a.png
    - images/c.png
    - images/r.png
    - images/s.png
    - images/password.jpg
    - images/register.jpg


  fonts:
    - family: vazir
      fonts:
        - asset: fonts/vazir_fd_medium_wol.ttf
 
